More Features for render_explanation
XAI-Demonstrator/visualime pull request #45
Opened 2023-04-14 09:36 UTC by Bergschaf

2023-04-14 09:50 UTC, ionicsolutions requested changes
Sieht schon sehr gut aus!

2023-04-14 09:50 UTC, ionicsolutions commented on visualime/explain.py
> +    max_num_of_segments: Optional[int] = None,
Lass uns diese Parameter als "keyword only" markieren: https://peps.python.org/pep-3102/

2023-04-14 09:50 UTC, ionicsolutions commented on visualime/explain.py
> +    num_of_segments: Optional[int] = None,
`coverage` sollte einen Default-Wert haben, so dass die Funktion in jedem Fall läuft, wenn man nur `image`, `segment_mask` und `segment_weights` angibt.

2023-04-14 09:50 UTC, ionicsolutions commented on visualime/explain.py
>          E.g., if set to 0.2 (the default), about 20% of the image are colored.
Default-Wert hier abgleichen mit dem tatsächlichen Default-Wert

2023-04-14 09:50 UTC, ionicsolutions commented on visualime/explain.py
> +        The maximum number of segments to be colored.
Kleinigkeit: Bitte den Docstring einheitlich formatieren, d.h. Leerzeilen einfügen wie bei den anderen Parametern.

2023-04-14 09:50 UTC, ionicsolutions commented on visualime/explain.py
> +        The maximum number of segments to be colored.
Hier müsste noch klar gemacht werden, dass das "pro Klasse/Farbe" ist, d.h. wenn ich "5" angebe und sowohl `positive` als auch `negative` nicht `None` sind, dann werden 5 positive und 5 negative eingefärbt. Das gilt auch für `coverage`.

2023-04-17 06:46 UTC, Bergschaf commented on visualime/explain.py
> +        The maximum number of segments to be colored.
Ich würde es eher so machen, das diese Werte absolut sind, d.h. es wird z.B. immer die anzahl on num_of_segments eingefärbt, egal ob nur die positiven oder auch die negativen segemente eingefärbt werden.

2023-04-19 11:19 UTC, merged